use `__EMSCRIPTEN__` and refactor

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -174,13 +174,13 @@ fi
 # default parameters
 container_engine="auto"
 cpu=""
-cross_compile="yes"
+cross_compile="no"
 cross_prefix=""
 host_cc="cc"
-EXTRA_CFLAGS=" -m32 -s USE_ZLIB=1 "
-EXTRA_CXXFLAGS=" -m32 "
+EXTRA_CFLAGS=""
+EXTRA_CXXFLAGS=""
 EXTRA_OBJCFLAGS=""
-EXTRA_LDFLAGS=" -m32 "
+EXTRA_LDFLAGS=""
 
 # Default value for a variable defining feature "foo".
 #  * foo="no"  feature will only be used if --enable-foo arg is given
@@ -240,6 +240,7 @@ done
 
 default_cflags='-O2 -g'
 git_submodules_action="update"
+docs="auto"
 EXESUF=""
 system="yes"
 linux_user=""
@@ -470,6 +471,10 @@ for opt do
   --cross-cc-*)
   ;;
   --cross-prefix-*)
+  ;;
+  --enable-docs) docs=enabled
+  ;;
+  --disable-docs) docs=disabled
   ;;
   --cpu=*)
   ;;
@@ -779,6 +784,21 @@ meson="$(cd pyvenv/bin; pwd)/meson"
 mkvenv_online_flag=""
 if test "$download" = "enabled" ; then
     mkvenv_online_flag=" --online"
+fi
+
+if test "$docs" != "disabled" ; then
+    if ! $mkvenv ensuregroup \
+         $(test "$docs" = "enabled" && echo "$mkvenv_online_flag") \
+         ${source_path}/pythondeps.toml docs;
+    then
+        if test "$docs" = "enabled" ; then
+            exit 1
+        fi
+        echo "Sphinx not found/usable, disabling docs."
+        docs=disabled
+    else
+        docs=enabled
+    fi
 fi
 
 # Probe for ninja
@@ -1319,6 +1339,7 @@ write_target_makefile() {
 # tests might fail. Prefer to keep the relevant files in their own
 # directory and symlink the directory instead.
 LINKS="Makefile"
+LINKS="$LINKS docs/config"
 LINKS="$LINKS pc-bios/optionrom/Makefile"
 LINKS="$LINKS pc-bios/s390-ccw/Makefile"
 LINKS="$LINKS pc-bios/vof/Makefile"
@@ -1405,11 +1426,9 @@ echo "GENISOIMAGE=$genisoimage" >> $config_host_mak
 echo "MESON=$meson" >> $config_host_mak
 echo "NINJA=$ninja" >> $config_host_mak
 echo "EXESUF=$EXESUF" >> $config_host_mak
-echo "CONFIG_EMSCRIPTEN=y" >> $config_host_mak
 if test "$default_targets" = "yes"; then
   echo "CONFIG_DEFAULT_TARGETS=y" >> $config_host_mak
 fi
-
 
 # contrib/plugins configuration
 echo "# Automatically generated by configure - do not modify" > contrib/plugins/$config_host_mak
@@ -1417,6 +1436,15 @@ echo "SRC_PATH=$source_path/contrib/plugins" >> contrib/plugins/$config_host_mak
 echo "PKG_CONFIG=${pkg_config}" >> contrib/plugins/$config_host_mak
 echo "CC=$cc $CPU_CFLAGS" >> contrib/plugins/$config_host_mak
 echo "CFLAGS=${CFLAGS-$default_cflags} $EXTRA_CFLAGS" >> contrib/plugins/$config_host_mak
+if test "$host_os" = windows; then
+  echo "DLLTOOL=$dlltool" >> contrib/plugins/$config_host_mak
+fi
+if test "$host_os" = darwin; then
+  echo "CONFIG_DARWIN=y" >> contrib/plugins/$config_host_mak
+fi
+if test "$host_os" = windows; then
+  echo "CONFIG_WIN32=y" >> contrib/plugins/$config_host_mak
+fi
 
 # tests/tcg configuration
 mkdir -p tests/tcg
@@ -1582,6 +1610,7 @@ if test "$skip_meson" = no; then
 
   # QEMU options
   test "$cfi" != false && meson_option_add "-Dcfi=$cfi" "-Db_lto=$cfi"
+  test "$docs" != auto && meson_option_add "-Ddocs=$docs"
   test -n "${LIB_FUZZING_ENGINE+xxx}" && meson_option_add "-Dfuzzing_engine=$LIB_FUZZING_ENGINE"
   test "$plugins" = yes && meson_option_add "-Dplugins=true"
   test "$tcg" != enabled && meson_option_add "-Dtcg=$tcg"
